name: comparatorr
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0-334.3.beta

dependencies:
  custom_pdf_converter: ^3.10.4
  file_picker: ^8.1.3
  flutter:
    sdk: flutter
  get: ^4.6.6
  google_mlkit_text_recognition: ^0.14.0
  menu_bar: ^0.5.3
  pdf: ^3.11.1
  pretty_diff_text: ^2.0.0
  syncfusion_flutter_pdf: ^27.1.57
  text2pdf: ^0.0.2
  tflite_flutter: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
